### ISSUE TITLE
Make filters smarter

### ISSUE THREAD

**Issue by jifeon** [apsavin/pgrights#1]
## How to reproduce

1. Consider you have a table name in camel case, like `siteDomains`
2. You need to filter out other tables and you remember, that needed table contains domains. You type into filter `domain`

## What's expected?

You see `siteDomains` table

![image](https://user-images.githubusercontent.com/384223/50000737-09a53280-ffcd-11e8-8b78-0001af472201.png)

## Actual result

You see nothing, since filter is case sensitive

![image](https://user-images.githubusercontent.com/384223/50000747-13c73100-ffcd-11e8-9d85-3524174983e4.png)

**Comment by jifeon** [comment]
It would be nice to have jetbrains-like filter. For example: `sido` should match **`si`**`te`**`Do`**`mains` as well

**Comment by apsavin** [comment]
The initial case fixed in https://github.com/apsavin/pgrights/commit/3fb059ec912a6543f47458219a69184d552f799c

The issue will be open because of your comment above :)

**Comment by apsavin** [comment]
Fixed into b46bd4a104e1457a5a72226748cf57e8f8176a7c
