### ISSUE TITLE
MonacoWebpackPlugin version issue 

### ISSUE THREAD

**Issue by Stvchm9703** [apsavin/pgrights#5]
env = win10, node=13.7.0

run flow :  npm run build-dll

error message :  Error: Cannot find module 'monaco-editor\esm\vs\editor\contrib\gotoSymbol\goToCommands'

after tracing, the `monaco-editor-webpack-plugin` package is removed the related feature `gotoSymbol` 

suggestion :  

ignore the issue by adding `features: ['!gotoSymbol']`, if there are no dependence on the feature.

@webpack.config.base.js , line42~48 
```
 plugins: [
    new MonacoWebpackPlugin({
      // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
      languages: ['pgsql'],
      features: ['!gotoSymbol'], // <<- add this
    }),
  ]
```

**Comment by apsavin** [comment]
Hi @Stvchm9703!

Thanks for the report, but I can't reproduce it. How did you install dependencies? Did you use `yarn` or `npm`?

**Comment by Stvchm9703** [comment]
I just run `npm i` and `npm i -D`  before `npm run build-dll`

**Comment by apsavin** [comment]
I think that's the cause of the issue. Try to use `yarn`: npm ignores `yarn.lock`.

By the way, why do you want to use dev version of the app? Would be interesting to know.

**Comment by Stvchm9703** [comment]
😆  since the developing environment of my project is Window 10, and there are no release version of window in this project. Therefore, try and run

**Comment by apsavin** [comment]
You can try to build production version with `yarn && yarn package`.

Or development version with `yarn && yarn dev`.

I think it should work. Tell me if you'll face any issues!

**Comment by Stvchm9703** [comment]
Thanks for replying, cheers 🥂
